name: GoReleaser

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner to use for the job"
        required: false
        type: string
        default: "ubuntu-latest"
      go-version:
        description: "Go version to use"
        required: false
        type: string
        default: "stable"
      goreleaser-version:
        description: "GoReleaser version to use"
        required: false
        type: string
        default: "~> v2"
      goreleaser-args:
        description: "Arguments to pass to GoReleaser"
        required: false
        type: string
        default: "release --clean"
      working-directory:
        description: "Working directory for the build"
        required: false
        type: string
        default: "."
      enable-sbom:
        description: "Install syft to enable SBOM generation"
        required: false
        type: boolean
        default: true

jobs:
  goreleaser:
    name: "GoReleaser"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install syft
        if: inputs.enable-sbom
        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: ${{ inputs.goreleaser-version }}
          args: ${{ inputs.goreleaser-args }}
          workdir: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
