name: GoReleaser

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner to use for the job"
        required: false
        type: string
        default: "ubuntu-latest"
      go-version:
        description: "Go version to use"
        required: false
        type: string
        default: "stable"
      goreleaser-version:
        description: "GoReleaser version to use"
        required: false
        type: string
        default: "~> v2"
      goreleaser-args:
        description: "Arguments to pass to GoReleaser"
        required: false
        type: string
        default: "release --clean"
      working-directory:
        description: "Working directory for the build"
        required: false
        type: string
        default: "."

jobs:
  goreleaser:
    name: "GoReleaser"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
        with:
          distribution: goreleaser
          version: ${{ inputs.goreleaser-version }}
          args: ${{ inputs.goreleaser-args }}
          workdir: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
